spring.application.name=backend


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.show-sql=true

jwt.secret=${SECRET}
jwt.lifetime=${LIFETIME}